// frontend/src/pages/Dashboard.jsx
import { Routes, Route, Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Templates from './Templates';
import Overview from './Overview';
import ClientDetail from './ClientDetail';
import Settings from './Settings';
import { LayoutDashboard, FileText, LogOut, Settings as SettingsIcon } from 'lucide-react';

export default function Dashboard() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const navs = [
    { path: '/dashboard', label: 'Overview', icon: LayoutDashboard },
    { path: '/dashboard/templates', label: 'Templates', icon: FileText },
    { path: '/dashboard/settings', label: 'Settings', icon: SettingsIcon },
  ];

  const navItemStyle = (isActive) => ({
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '9px 12px',
    borderRadius: 'var(--radius-md)',
    fontSize: '14px',
    fontWeight: isActive ? '600' : '500',
    color: isActive ? 'var(--brand)' : 'var(--text-secondary)',
    background: isActive ? 'var(--brand-light)' : 'transparent',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'all 0.15s',
    marginBottom: '2px'
  });

  const sidebarStyle = {
    width: '240px',
    background: 'var(--bg-card)',
    borderRight: '1px solid var(--border)',
    height: '100vh',
    position: 'fixed',
    left: 0, top: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: '20px 16px'
  };

  return (
    <div className="min-h-screen">
      <aside style={sidebarStyle} className="sidebar-override">
        <div style={{ padding: '0 8px 24px 8px', borderBottom: '1px solid var(--border)', marginBottom: '16px' }}>
          <div style={{
            overflow: 'hidden',
            whiteSpace: 'nowrap',
            textOverflow: 'ellipsis',
            maxWidth: '180px',
            fontWeight: '700',
            fontSize: '15px',
            color: 'var(--text-primary)'
          }}>
            {user?.agencyName || 'Agency'}
          </div>
          <p style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '2px 0 0 0' }}>Agency Portal</p>
        </div>
        <nav style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
          {navs.map(n => {
            const Icon = n.icon;
            const isActive = location.pathname === n.path || (n.path === '/dashboard' && location.pathname.startsWith('/dashboard/client/')) || (n.path !== '/dashboard' && location.pathname.startsWith(n.path));
            return (
              <Link key={n.path} to={n.path} style={navItemStyle(isActive)}>
                <Icon size={18} />
                {n.label}
              </Link>
            );
          })}
          
          <button 
            onClick={handleLogout} 
            style={{ ...navItemStyle(false), marginTop: 'auto', color: 'var(--danger)' }}
            onMouseEnter={e => { e.currentTarget.style.background = 'var(--danger-light)' }}
            onMouseLeave={e => { e.currentTarget.style.background = 'transparent' }}
          >
            <LogOut size={18} />
            Logout
          </button>
        </nav>
      </aside>

      <main style={{ marginLeft: '240px', padding: '32px' }}>
        <Routes>
          <Route path="/" element={<Overview />} />
          <Route path="/templates" element={<Templates />} />
          <Route path="/client/:id" element={<ClientDetail />} />
          <Route path="/settings" element={<Settings />} />
        </Routes>
      </main>
    </div>
  );
}

// frontend-angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, ActivatedRoute, NavigationEnd } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { LucideAngularModule, LayoutDashboard, FileText, Settings, LogOut } from 'lucide-angular';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  template: `
    <div class="min-h-screen">
      <!-- Sidebar -->
      <aside [ngStyle]="sidebarStyle" class="sidebar-override">
        <div style="padding: 0 8px 24px 8px; border-bottom: 1px solid var(--border); margin-bottom: 16px;">
          <!-- Agency name -->
          <div style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis; max-width: 180px; font-weight: 700; font-size: 15px; color: var(--text-primary);">
            {{ auth.user()?.agencyName || 'Agency' }}
          </div>
          <!-- Onvora brand label -->
          <p style="font-size: 11px; color: var(--text-muted); margin: 2px 0 0 0; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase;">Onvora</p>
        </div>
        
        <nav style="flex: 1; display: flex; flex-direction: column;">
          <a *ngFor="let n of navs" 
             [routerLink]="n.path" 
             [ngStyle]="navItemStyle(isActive(n.path))"
             [style.background]="isActive(n.path) ? 'var(--brand-light)' : 'transparent'"
             [style.color]="isActive(n.path) ? 'var(--brand)' : 'var(--text-secondary)'"
             [style.font-weight]="isActive(n.path) ? '600' : '500'">
            <lucide-icon [name]="n.iconName" [size]="18"></lucide-icon>
            {{ n.label }}
          </a>
          
          <button 
            (click)="handleLogout()" 
            [ngStyle]="logoutStyle"
            (mouseenter)="isLogoutHovered = true"
            (mouseleave)="isLogoutHovered = false"
            [style.background]="isLogoutHovered ? 'var(--danger-light)' : 'transparent'"
          >
            <lucide-icon name="LogOut" [size]="18"></lucide-icon>
            Logout
          </button>
        </nav>
      </aside>

      <!-- Main Content -->
      <main style="margin-left: 240px; padding: 32px;">
        <router-outlet></router-outlet>
      </main>
    </div>
  `
})
export class DashboardComponent {
  auth = inject(AuthService);
  router = inject(Router);
  currentPath = '';
  isLogoutHovered = false;

  readonly LayoutDashboard = LayoutDashboard;
  readonly FileText = FileText;
  readonly SettingsIcon = Settings;
  readonly LogOut = LogOut;

  navs = [
    { path: '/dashboard', label: 'Overview', iconName: 'LayoutDashboard' },
    { path: '/dashboard/templates', label: 'Templates', iconName: 'FileText' },
    { path: '/dashboard/settings', label: 'Settings', iconName: 'Settings' },
  ];

  constructor() {
    this.currentPath = this.router.url;
    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe((event: any) => {
      this.currentPath = event.urlAfterRedirects;
    });
  }

  handleLogout() {
    this.auth.logout();
    this.router.navigate(['/login']);
  }

  isActive(path: string): boolean {
    if (path === '/dashboard') {
      return this.currentPath === '/dashboard' || this.currentPath.startsWith('/dashboard/client/');
    }
    return this.currentPath.startsWith(path);
  }

  navItemStyle(isActive: boolean): any {
    return {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      padding: '9px 12px',
      borderRadius: 'var(--radius-md)',
      fontSize: '14px',
      cursor: 'pointer',
      textDecoration: 'none',
      transition: 'all 0.15s',
      marginBottom: '2px'
    };
  }

  get logoutStyle(): any {
    return {
      ...this.navItemStyle(false),
      marginTop: 'auto',
      color: 'var(--danger)',
      border: 'none',
    };
  }

  sidebarStyle = {
    width: '240px',
    background: 'var(--bg-card)',
    borderRight: '1px solid var(--border)',
    height: '100vh',
    position: 'fixed' as const,
    left: '0',
    top: '0',
    display: 'flex',
    flexDirection: 'column' as const,
    padding: '20px 16px'
  };
}
