// frontend-angular/src/app/pages/client-portal/contract-viewer/contract-viewer.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { OnboardingService } from '../../../services/onboarding.service';
import { environment } from '../../../../environments/environment';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-contract-viewer',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
    <div class="p-6">
      <h2 class="text-2xl font-bold text-gray-800 mb-4">
        Step 3: Review & Sign Contract
      </h2>

      <p class="text-gray-600 mb-6">
        Please review the agreement below carefully before signing.
      </p>

      <div class="contract-box whitespace-pre-wrap">
        {{ contractText }}
      </div>

      <form (ngSubmit)="handleSign($event)" class="border-t pt-6">

        <!-- Signature Field -->
        <div class="mb-4">

          <label class="block text-sm font-medium text-gray-700 mb-2">
            Electronic Signature (Type your full name)
          </label>

          <div class="signature-input-wrapper">

            <!-- Pen icon disappears while typing -->
            <div
              class="signature-icon"
              [class.hidden]="signature.trim().length > 0"
            >
              <lucide-icon
                name="PenTool"
                [size]="18"
                class="text-gray-400"
              ></lucide-icon>
            </div>

            <input
              type="text"
              required
              class="signature-input"
              placeholder="e.g. John Doe"
              [(ngModel)]="signature"
              name="signature"
              autocomplete="off"
            />

          </div>

          <!-- Live signature preview -->
          <div
            *ngIf="signature.trim()"
            style="
              margin-top: 16px;
              background: #F8FAFC;
              padding: 16px 20px;
              border-left: 3px solid var(--brand);
              border-top-right-radius: var(--radius-md);
              border-bottom-right-radius: var(--radius-md);
            "
          >
            <div
              style="
                font-family: 'Brush Script MT', cursive;
                font-size: 28px;
                color: var(--brand-dark);
                margin-bottom: 4px;
              "
            >
              {{ signature }}
            </div>

            <div
              style="
                font-size: 11px;
                color: var(--text-muted);
                text-transform: uppercase;
                letter-spacing: 0.05em;
              "
            >
              Digitally signed on {{ today | date:'mediumDate' }}
            </div>
          </div>
        </div>

        <p class="text-xs text-gray-500 mb-6">
          By clicking "Sign & Continue", you acknowledge that this electronic
          signature is fully binding and holds the same legal validity as a
          physical signature.
        </p>

        <div class="flex justify-end pt-4">
          <button
            type="submit"
            [disabled]="loading || !signature.trim()"
            class="btn-primary"
            [class.btn-loading]="loading"
            [class.opacity-50]="loading || !signature.trim()"
            style="
              padding: 12px 28px;
              background: var(--brand);
              color: #fff;
            "
          >
            {{ loading ? 'Processing...' : 'Sign & Continue →' }}
          </button>
        </div>

      </form>
    </div>
  `,
  styles: [`
    .signature-input-wrapper {
      position: relative;
    }

    .signature-icon {
      position: absolute;
      left: 14px;
      top: 50%;
      transform: translateY(-50%);
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;
      transition: opacity 0.2s ease;
      z-index: 2;
    }

    .signature-icon.hidden {
      opacity: 0;
    }

    .signature-input {
      width: 100%;
      border: 1px solid #D1D5DB;
      border-radius: 8px;
      padding: 14px 16px 14px 42px;
      font-family: serif;
      font-size: 18px;
      color: #1F2937;
      transition: all 0.2s ease;
      background: #fff;
    }

    .signature-input:focus {
      outline: none;
      border-color: #3B82F6;
      box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.15);
    }

    /* Remove extra left padding while typing */
    .signature-input:not(:placeholder-shown) {
      padding-left: 16px;
    }
  `]
})
export class ContractViewerComponent {

  onboarding = inject(OnboardingService);
  private http = inject(HttpClient);

  signature = '';
  loading = false;
  today = new Date();

  get contractText(): string {
    const template = this.onboarding.sessionData()?.template;

    return (
      template?.contractText ||
      'This is a standard service agreement. By typing your name below, you agree to the terms and conditions set forth by the Agency.'
    );
  }

  async handleSign(e: Event) {
    e.preventDefault();

    if (!this.signature.trim()) {
      alert('Please type your signature to agree.');
      return;
    }

    this.loading = true;

    try {
      const token = this.onboarding.sessionData().token;

      const data = await this.http.post<any>(
        `${environment.apiUrl}/api/onboarding/${token}/sign`,
        {
          signatureData: this.signature
        }
      ).toPromise();

      if (data?.nextStep) {
        this.onboarding.updateStep(data.nextStep);
      }

    } catch (err: any) {

      alert(
        err?.error?.message ||
        err?.message ||
        'Failed to sign contract'
      );

    } finally {
      this.loading = false;
    }
  }
}

// frontend/src/pages/ContractViewer.jsx
import { useState } from 'react';
import { useOnboarding } from '../context/OnboardingContext';
import { PenTool } from 'lucide-react';

export default function ContractViewer() {
  const { sessionData, updateStep } = useOnboarding();
  const [signature, setSignature] = useState('');
  const [loading, setLoading] = useState(false);

  const { template } = sessionData;
  const contractText = template?.contractText || 
    "This is a standard service agreement. By typing your name below, you agree to the terms and conditions set forth by the Agency.";

  const handleSign = async (e) => {
    e.preventDefault();
    if (!signature.trim()) return alert("Please type your signature to agree.");

    setLoading(true);
    try {
      const res = await fetch(`${import.meta.env.VITE_API_BASE_URL || "http://localhost:5000"}/api/onboarding/${sessionData.token}/sign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ signatureData: signature })
      });
      const data = await res.json();
      if (res.ok) {
        updateStep(data.nextStep);
      } else {
        alert(data.message || 'Failed to sign contract');
      }
    } catch (err) {
      alert(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold text-gray-800 mb-4">Step 3: Review & Sign Contract</h2>
      <p className="text-gray-600 mb-6">Please review the agreement below carefully before signing.</p>
      
      <div className="contract-box whitespace-pre-wrap">
        {contractText}
      </div>

      <form onSubmit={handleSign} className="border-t pt-6">
        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Electronic Signature (Type your full name)
          </label>
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <PenTool size={18} className="text-gray-400" />
            </div>
            <input
              type="text"
              required
              className="pl-10 block w-full border border-gray-300 rounded p-3 focus:ring-blue-500 focus:border-blue-500 font-serif text-lg text-gray-800"
              placeholder="e.g. John Doe"
              value={signature}
              onChange={(e) => setSignature(e.target.value)}
            />
          </div>
          {signature.trim() && (
            <div style={{
              marginTop: '16px',
              background: '#F8FAFC',
              padding: '16px 20px',
              borderLeft: '3px solid var(--brand)',
              borderTopRightRadius: 'var(--radius-md)',
              borderBottomRightRadius: 'var(--radius-md)'
            }}>
              <div style={{
                fontFamily: '"Brush Script MT", cursive',
                fontSize: '28px',
                color: 'var(--brand-dark)',
                marginBottom: '4px'
              }}>
                {signature}
              </div>
              <div style={{ fontSize: '11px', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                Digitally signed on {new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })}
              </div>
            </div>
          )}
        </div>

        <p className="text-xs text-gray-500 mb-6">
          By clicking "Sign & Continue", you acknowledge that this electronic signature is fully binding and holds the same legal 
          validity as a physical signature.
        </p>
        
        <div className="flex justify-end pt-4">
          <button
            type="submit"
            disabled={loading || !signature.trim()}
            className={`btn-primary ${loading ? 'btn-loading' : ''}`}
            style={{ padding:'12px 28px', background:'var(--brand)', color:'#fff' }}
          >
            {loading ? 'Processing...' : 'Sign & Continue →'}
          </button>
        </div>
      </form>
    </div>
  );
}
